### ISSUE TITLE
Breaking change! using email instead of username for loggin ?

### ISSUE THREAD

**Issue by kevariable** [laferhem/laravel-email-otp#2]
how about it? @fnlaai @79r

**Comment by fnlaai** [comment]
the field is email, but it can contain email or username, just don't set input type to email, set to text instead. In backend you check email field wheter it email or username, first db query as email, if it's not there, db query as username.

**Comment by kevariable** [comment]
A good idea to the user experience, thanks your feedback @fnlaai
